export const data = [
  {
    id: 1,
    customerId: "C001",
    teacherName: "John Doe",
    department: "Mathematics",
    student: "Alice",
    status: "Active",
  },
  {
    id: 2,
    customerId: "C002",
    teacherName: "Jane Smith",
    department: "Physics",
    student: "Bob",
    status: "Inactive",
  },
  {
    id: 3,
    customerId: "C003",
    teacherName: "Michael Johnson",
    department: "Biology",
    student: "Charlie",
    status: "Active",
  },
  {
    id: 4,
    customerId: "C004",
    teacherName: "Emily Brown",
    department: "Chemistry",
    student: "David",
    status: "Inactive",
  },
  {
    id: 5,
    customerId: "C005",
    teacherName: "Sarah Wilson",
    department: "History",
    student: "Emma",
    status: "Active",
  },
  {
    id: 6,
    customerId: "C006",
    teacherName: "Daniel Taylor",
    department: "English",
    student: "Frank",
    status: "Inactive",
  },
  {
    id: 7,
    customerId: "C007",
    teacherName: "Olivia Martinez",
    department: "Computer Science",
    student: "Grace",
    status: "Active",
  },
  {
    id: 8,
    customerId: "C008",
    teacherName: "William Anderson",
    department: "Geography",
    student: "Henry",
    status: "Inactive",
  },
  {
    id: 9,
    customerId: "C009",
    teacherName: "Sophia Hernandez",
    department: "Economics",
    student: "Isabella",
    status: "Active",
  },
];
