export const data = [
  {
    id: 1,
    customerId: "C001",
    teacherName: "John Doe",
    department: "Mathematics",
    student: "Alice",
    status: "Active",
  },
  {
    id: 2,
    customerId: "C002",
    teacherName: "Jane Smith",
    department: "Physics",
    student: "Bob",
    status: "Inactive",
  },
  {
    id: 3,
    customerId: "C003",
    teacherName: "Michael Johnson",
    department: "Biology",
    student: "Charlie",
    status: "Active",
  },
  {
    id: 4,
    customerId: "C004",
    teacherName: "Emily Brown",
    department: "Chemistry",
    student: "David",
    status: "Inactive",
  },
  {
    id: 5,
    customerId: "C005",
    teacherName: "Sarah Wilson",
    department: "History",
    student: "Emma",
    status: "Active",
  },
  {
    id: 6,
    customerId: "C006",
    teacherName: "Daniel Taylor",
    department: "English",
    student: "Frank",
    status: "Inactive",
  },
  {
    id: 7,
    customerId: "C007",
    teacherName: "Olivia Martinez",
    department: "Computer Science",
    student: "Grace",
    status: "Active",
  },
  {
    id: 8,
    customerId: "C008",
    teacherName: "William Anderson",
    department: "Geography",
    student: "Henry",
    status: "Inactive",
  },
  {
    id: 9,
    customerId: "C009",
    teacherName: "Sophia Hernandez",
    department: "Economics",
    student: "Isabella",
    status: "Active",
  },
  {
    id: 10,
    customerId: "C010",
    teacherName: "James Gonzalez",
    department: "Art",
    student: "Jack",
    status: "Inactive",
  },
  {
    id: 11,
    customerId: "C011",
    teacherName: "David Lopez",
    department: "Music",
    student: "Lily",
    status: "Active",
  },
  {
    id: 12,
    customerId: "C012",
    teacherName: "Emma Perez",
    department: "Physical Education",
    student: "Mason",
    status: "Inactive",
  },
  {
    id: 13,
    customerId: "C013",
    teacherName: "Benjamin Carter",
    department: "Political Science",
    student: "Noah",
    status: "Active",
  },
  {
    id: 14,
    customerId: "C014",
    teacherName: "Mia Evans",
    department: "Psychology",
    student: "Olivia",
    status: "Inactive",
  },
  {
    id: 15,
    customerId: "C015",
    teacherName: "Ethan Turner",
    department: "Sociology",
    student: "Sophia",
    status: "Active",
  },
  {
    id: 16,
    customerId: "C016",
    teacherName: "Chloe King",
    department: "Statistics",
    student: "Thomas",
    status: "Inactive",
  },
  {
    id: 17,
    customerId: "C017",
    teacherName: "Liam Collins",
    department: "Philosophy",
    student: "Victoria",
    status: "Active",
  },
  {
    id: 18,
    customerId: "C018",
    teacherName: "Ava Stewart",
    department: "Anthropology",
    student: "William",
    status: "Inactive",
  },
  {
    id: 19,
    customerId: "C019",
    teacherName: "Logan Rivera",
    department: "Engineering",
    student: "Zoe",
    status: "Active",
  },
  {
    id: 20,
    customerId: "C020",
    teacherName: "Harper Ward",
    department: "Medicine",
    student: "Elijah",
    status: "Inactive",
  },
];
